# Outputs for GCP VPC Module
# Generated by X-Terraform Agent v0.0.1

output "network_id" {
  description = "The ID of the VPC network"
  value       = google_compute_network.vpc.id
}

output "network_name" {
  description = "The name of the VPC network"
  value       = google_compute_network.vpc.name
}

output "network_self_link" {
  description = "The self-link of the VPC network"
  value       = google_compute_network.vpc.self_link
}

output "public_subnet_ids" {
  description = "List of IDs of public subnets"
  value       = google_compute_subnetwork.public[*].id
}

output "public_subnet_names" {
  description = "List of names of public subnets"
  value       = google_compute_subnetwork.public[*].name
}

output "public_subnet_self_links" {
  description = "List of self-links of public subnets"
  value       = google_compute_subnetwork.public[*].self_link
}

output "private_subnet_ids" {
  description = "List of IDs of private subnets"
  value       = google_compute_subnetwork.private[*].id
}

output "private_subnet_names" {
  description = "List of names of private subnets"
  value       = google_compute_subnetwork.private[*].name
}

output "private_subnet_self_links" {
  description = "List of self-links of private subnets"
  value       = google_compute_subnetwork.private[*].self_link
}

output "router_id" {
  description = "The ID of the Cloud Router"
  value       = var.enable_nat ? google_compute_router.router[0].id : null
}

output "router_name" {
  description = "The name of the Cloud Router"
  value       = var.enable_nat ? google_compute_router.router[0].name : null
}

output "nat_id" {
  description = "The ID of the Cloud NAT"
  value       = var.enable_nat ? google_compute_router_nat.nat[0].id : null
}

output "nat_name" {
  description = "The name of the Cloud NAT"
  value       = var.enable_nat ? google_compute_router_nat.nat[0].name : null
}

output "firewall_rule_names" {
  description = "List of firewall rule names"
  value = {
    ssh     = var.enable_ssh_access ? google_compute_firewall.ssh[0].name : null
    http    = var.enable_http_access ? google_compute_firewall.http[0].name : null
    https   = var.enable_https_access ? google_compute_firewall.https[0].name : null
    internal = google_compute_firewall.internal.name
  }
}

output "subnet_count" {
  description = "Number of subnets created"
  value = {
    public  = length(var.public_subnet_ranges)
    private = length(var.private_subnet_ranges)
    total   = length(var.public_subnet_ranges) + length(var.private_subnet_ranges)
  }
}

output "firewall_count" {
  description = "Number of firewall rules created"
  value = {
    ssh      = var.enable_ssh_access ? 1 : 0
    http     = var.enable_http_access ? 1 : 0
    https    = var.enable_https_access ? 1 : 0
    internal = 1
    total    = (var.enable_ssh_access ? 1 : 0) + (var.enable_http_access ? 1 : 0) + (var.enable_https_access ? 1 : 0) + 1
  }
}

output "module_summary" {
  description = "Summary of the VPC module configuration"
  value = {
    network_name           = var.network_name
    vpc_cidr_block         = var.vpc_cidr_block
    public_subnets         = length(var.public_subnet_ranges)
    private_subnets        = length(var.private_subnet_ranges)
    regions                = length(var.regions)
    nat_enabled            = var.enable_nat
    ssh_access_enabled     = var.enable_ssh_access
    http_access_enabled    = var.enable_http_access
    https_access_enabled   = var.enable_https_access
  }
} 