name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build package
      run: |
        chmod +x scripts/build-package.sh
        ./scripts/build-package.sh
        
    - name: Generate release notes
      id: release_notes
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "## X-Terraform Agent $VERSION" > RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### 🚀 What's New" >> RELEASE_NOTES.md
        echo "- AI-powered Terraform assistant with offline capabilities" >> RELEASE_NOTES.md
        echo "- Zero internet dependency after installation" >> RELEASE_NOTES.md
        echo "- Complete package with Python, Ollama, and codellama:7b-instruct model" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### 📦 Installation" >> RELEASE_NOTES.md
        echo "1. Download the package for your platform" >> RELEASE_NOTES.md
        echo "2. Extract: \`tar -xzf x-terraform-agent-$VERSION-*.tar.gz\`" >> RELEASE_NOTES.md
        echo "3. Install: \`./install.sh\`" >> RELEASE_NOTES.md
        echo "4. Run: \`./scripts/agent-cli.sh start\`" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### 🔗 Links" >> RELEASE_NOTES.md
        echo "- [Repository](https://github.com/inderanz/x-terraform)" >> RELEASE_NOTES.md
        echo "- [Documentation](https://github.com/inderanz/x-terraform#readme)" >> RELEASE_NOTES.md
        echo "- [Developer](https://anzx.ai/)" >> RELEASE_NOTES.md
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.tar.gz
          dist/*.tar.gz.sha256
          dist/install.sh
          dist/release-notes-*.md
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 